name: Code coverage - Node 24

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-code-coverage:
    name: Code coverage - Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    env:
      node-version: 24

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Run npm CI
        shell: bash
        run: npm ci

      - name: Install jest and run code coverage
        shell: bash
        run: |
          npm install jest --global
          NODE_OPTIONS=--experimental-vm-modules NODE_NO_WARNINGS=1 npx jest --verbose --collectCoverage
