
name: Test - get LTS versions
on:
  push:

jobs:
  get-lts-versions:
    name: Fetch LTS versions
    runs-on: ubuntu-latest
    env:
      node-version: 24

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check for Golang LTS versions
        uses: ./
        with:
          language: "go"
          versions_number: "3"
